mysite/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#main'
  get '/welcome', to: 'welcome#home'
  get '/welcome/about', to: 'welcome#about'

  resources :articles
end

mysite/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

mysite/app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 30 }
end

mysite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

mysite/app/controllers/articles_controller.rb
## Controller
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def create; end

end

mysite/app/controllers/welcome_controller.rb
## Controller
class WelcomeController < ApplicationController
  def main; end

  def home; end

  def about; end
end

mysite/app/helpers/application_helper.rb
module ApplicationHelper
end

mysite/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% @article.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

mysite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mysite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

mysite/app/views/welcome/about.html.erb
<h1> This is about Page </h1>
<%= link_to 'Home Page', welcome_path =%>

mysite/app/views/welcome/home.html.erb
<h1> This is Home Page </h1>
<%= link_to 'About Page', welcome_about_path =%>
<%= link_to 'Main Page', root_path =%>

mysite/app/views/welcome/main.html.erb
<h1> Main Page </h1>
<%= link_to 'Home Page', welcome_path =%>
<%= link_to 'About Page', welcome_about_path =%>